# +======================================================================+
# | CERTEUS - pre-commit (Ruff + format + drobne sanity checks)          |
# +======================================================================+

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: local
    hooks:
      - id: certeus-header-docstring-gate
        name: CERTEUS header/docstring gate
        entry: python scripts/check_headers.py
        language: system
        files: \.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
