# +=====================================================================+
# |                          CERTEUS — HEART                            |
# +=====================================================================+
# | FILE: .pre-commit-config.yaml                                       |
# | ROLE: Format / lint / sanity hooks (ruff, prettier, pytest, secrets)|
# +=====================================================================+

minimum_pre_commit_version: "3.7.0"

repos:
  # Ruff (lint + format)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
        stages: [pre-commit]
      - id: ruff-format
        stages: [pre-commit]

  # Prettier (mirror) — jedna pozycja, bez additional_dependencies
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v4.0.0-alpha.8
  hooks:
    - id: prettier
      stages: [pre-commit]
      files: >
        (\.md$|\.json$|\.ya?ml$|\.html?$|\.css$|\.js$|\.jsx$|\.ts$|\.tsx$)
        |(^clients/web/)
      exclude: >
        ^(node_modules/|dist/|build/|static/previews/|reports/|exports/|artifacts/|proof_artifacts/)

  # Standardowe utility hooki
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: detect-private-key
        stages: [pre-commit]
        # Blokuj klucze (lokalnie trzymasz, ale nie commituj)
        files: '(\.pem$|\.key$|\.pfx$|\.p12$|\.der$)'
      - id: check-added-large-files
        stages: [pre-commit]
        args: ["--maxkb=800"]

  # Lokalny szybki test (opcjonalnie można wyłączyć, ale zostawiam jak było)
  - repo: local
    hooks:
      - id: pytest
        name: pytest (fast)
        entry: uv run pytest -q
        language: system
        pass_filenames: false
        stages: [pre-commit]
