# +=====================================================================+
# |                          CERTEUS — HEART                            |
# +=====================================================================+
# | FILE: .pre-commit-config.yaml                                       |
# | ROLE: Format / lint / sanity hooks (ruff, prettier, pytest, secrets)|
# +=====================================================================+

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-prettier
    # Używaj tego taga — jest w repo mirrors-prettier:
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        # Regex plików do formatowania (JS/TS/HTML/CSS/MD/YAML + cały clients/web/)
        files: |-
          (\.md$|\.json$|\.ya?ml$|\.html?$|\.css$|\.js$|\.jsx$|\.ts$|\.tsx$)|(^clients/web/)
        # Wyklucz cache/build/artefakty:
        exclude: |-
          ^(node_modules/|dist/|build/|static/previews/|reports/|exports/|artifacts/|proof_artifacts/)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: check-added-large-files
        args: ["--maxkb=5120"]

  # Lokalne testy (szybkie). Wymaga uv + pytest w środowisku.
  - repo: local
    hooks:
      - id: pytest
        name: pytest (fast)
        entry: uv run pytest -q
        language: system
        pass_filenames: false
