# +=====================================================================+
# |                          CERTEUS — HEART                            |
# +=====================================================================+
# | FILE: .pre-commit-config.yaml                                       |
# | ROLE:                                                                |
# |  PL: Hooki jakości – ruff, pyright (opcjonalnie), pytest, YAML/JSON. |
# |  EN: Quality hooks – ruff, pyright (opt), pytest, YAML/JSON.         |
# +=====================================================================+

ci:
  autofix_prs: false
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ['--fix', '--exit-non-zero-on-fix']
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-prettier
    # Użyj stabilnego taga z repo mirrors-prettier:
    # możesz też dać 'v4.0.0-alpha.8' — ważne, żeby był format 'v...'
    rev: v3.3.3
    hooks:
      - id: prettier
        # Używamy apostrofów, żeby backslashy nie pożarł YAML
        files: '\.(js|ts|jsx|tsx|json|md|yaml|yml|css|scss|html)$'
        exclude: '^(node_modules/|dist/|build/|coverage/|out/|\.cache/|ingest_repo/|proof_artifacts/|.*\.min\.(js|css)$|.*\.lock$|uv\.lock$)'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: pytest
        name: pytest (fast)
        entry: uv run pytest -q
        language: system
        pass_filenames: false
        # 'commit' bywa oznaczany jako przestarzały — użyj 'pre-commit'
        stages: [pre-commit]

      - id: block-key-extensions
        name: 'forbid: key files (*.pem|*.key|*.pfx|*.p12|*.der)'
        entry: python scripts/hooks/block_key_extensions.py
        language: system
        pass_filenames: false
        types: [file]
        files: '(\.pem|\.key|\.pfx|\.p12|\.der)$'
