# Gitleaks configuration (minimal, redact output)
[rules]

[allowlist]
  description = "Allow test fixtures and sample hashes"
  paths = [
    "tests/",
    "docs/",
    "clients/web/",
    ".devkeys/",
    "security/bunker/",
    "scripts/runners/",
    "scripts/pfs/win_dokan_smoke.ps1",
  ]
