site_name: CERTEUS Docs
site_url: https://CERTEUS.github.io/certeus
theme:
  name: material
  language: en
nav:
  - Home: index.md
  - API: api/openapi.md
  - Observability: observability/README.md
plugins:
  - search
  - openapi:
      spec_dir: docs/api
      use_nav: false
markdown_extensions:
  - admonition
  - toc

