# +-------------------------------------------------------------+
# | CERTEUS Control System | ForgeHeader v3 - Enterprise     |
# | FILE: workspaces/certeus/mkdocs.yml                                      |
# | ROLE: Documentation configuration                                        |
# +-------------------------------------------------------------+

site_name: CERTEUS Documentation
site_description: Enterprise-Grade Verifiable Cognitive Intelligence Platform
site_url: https://certeus.io

theme:
  name: material
  logo: docs/assets/brand/certeus-favicon.svg
  features:
    - navigation.tabs
    - navigation.sections
    - toc.follow
    - content.code.copy
  palette:
    - scheme: default
      primary: blue
      accent: cyan

nav:
  - Home: index.md
  - Getting Started:
      - Quick Start: QUICKSTART.md
      - Concepts: CONCEPTS.md
  - Architecture: ARCHITECTURE.md
  - Deployment: DEPLOYMENT.md
  - SDK:
      - Overview: SDK.md
      - Python: sdk/python.md
      - TypeScript: sdk/typescript.md
      - Go: sdk/go.md
  - API:
      - Reference: api/openapi.md
      - Endpoints: ENDPOINTS.md
  - Security: SECURITY.md
  - Monitoring: MONITORING.md
  - Runbooks: runbooks/index.md
  - Tutorials: tutorials/index.md
  - Enterprise: ENTERPRISE.md
  - Troubleshooting: TROUBLESHOOTING.md

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CERTEUS/certeus

copyright: |
  &copy; 2024 CERTEUS Inc.
