# +-------------------------------------------------------------+
# |                          CERTEUS                            |
# +-------------------------------------------------------------+
# | FILE: mkdocs.yml                                            |
# | ROLE: Docs site config (Material)                           |
# | PLIK: mkdocs.yml                                            |
# | ROLA: Konfiguracja strony dokumentacji                      |
# +-------------------------------------------------------------+

site_name: CERTEUS Docs
site_url: https://CERTEUS.github.io/certeus
theme:
  name: material
  language: en
nav:
  - Home: index.md
  - API:
      - Overview: api/overview.md
      - Spec (OpenAPI): api/openapi.md
  - Runbooks:
      - CI Local: runbooks/ci_local.md
plugins:
  - search
markdown_extensions:
  - admonition
  - toc
