# +-------------------------------------------------------------+
# |                          CERTEUS                            |
# +-------------------------------------------------------------+
# | FILE: infra/docker-compose.local-infra.yml                |
# | ROLE: Project YAML manifest.                                |
# | PLIK: infra/docker-compose.local-infra.yml                |
# | ROLA: Manifest YAML projektu.                               |
# +-------------------------------------------------------------+

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: certeus
      POSTGRES_USER: certeus
      POSTGRES_PASSWORD: certeus
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  minio:
    image: quay.io/minio/minio:RELEASE.2024-04-18T19-09-19Z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports: ["9000:9000", "9001:9001"]
    volumes: [minio:/data]

volumes:
  pgdata: {}
  minio: {}
