# +-------------------------------------------------------------+
# |                          CERTEUS                            |
# +-------------------------------------------------------------+
# | FILE: observability/prometheus/prometheus.yml             |
# | ROLE: Project YAML manifest.                                |
# | PLIK: observability/prometheus/prometheus.yml             |
# | ROLA: Manifest YAML projektu.                               |
# +-------------------------------------------------------------+

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/recording_rules.yml

scrape_configs:
  - job_name: 'api_gateway'
    static_configs:
      - targets: ['api:8000']
  - job_name: 'proofgate'
    static_configs:
      - targets: ['proofgate:8081']

