global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/recording_rules.yml

scrape_configs:
  - job_name: 'api_gateway'
    static_configs:
      - targets: ['api:8000']
  - job_name: 'proofgate'
    static_configs:
      - targets: ['proofgate:8081']

