# +-------------------------------------------------------------+
# |                          CERTEUS                            |
# +-------------------------------------------------------------+
# | FILE: charts/certeus/templates/ingress.yaml               |
# | ROLE: Project YAML manifest.                                |
# | PLIK: charts/certeus/templates/ingress.yaml               |
# | ROLA: Manifest YAML projektu.                               |
# +-------------------------------------------------------------+

{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "certeus.fullname" . }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "certeus.fullname" $ }}-{{ .backend }}
                port:
                  name: http
          {{- end }}
    {{- end }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
{{- end }}
