# +-------------------------------------------------------------+
# |                          CERTEUS                            |
# +-------------------------------------------------------------+
# | FILE: infra/k8s/core.yaml                                 |
# +-------------------------------------------------------------+
# | CERTEUS Control System | ForgeHeader v3 - Enterprise     |
# | FILE: infra/k8s/core.yaml                                 |
# | ROLE: Core Kubernetes manifests for CERTEUS deployment    |
# +-------------------------------------------------------------+

apiVersion: v1
kind: Namespace
metadata:
  name: certeus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proofgate
  namespace: certeus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proofgate
  template:
    metadata:
      labels:
        app: proofgate
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        runAsNonRoot: true
      containers:
        - name: proofgate
          image: ghcr.io/org/repo/proofgate:v0.2.0
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "128Mi"
              cpu: "100m"
              ephemeral-storage: "2Gi"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
