# +-------------------------------------------------------------+
# |                          CERTEUS                            |
# +-------------------------------------------------------------+
# | FILE: docs/api/openapi.yaml                                 |
# | ROLE: OpenAPI placeholder for docs                          |
# | PLIK: docs/api/openapi.yaml                                 |
# | ROLA: Placeholder OpenAPI do renderowania                    |
# +-------------------------------------------------------------+

openapi: 3.0.3
info:
  title: CERTEUS API (placeholder)
  version: 0.0.1
paths:
  /health:
    get:
      summary: Healthcheck
      responses:
        '200':
          description: OK
