# +-------------------------------------------------------------+
# |                          CERTEUS                            |
# +-------------------------------------------------------------+
# | FILE: .github/workflows/api-changelog.yml                  |
# | ROLE: Generate API CHANGELOG on OpenAPI changes            |
# +-------------------------------------------------------------+

name: API Changelog

on:
  push:
    branches: [ main ]
    paths: [ 'docs/api/openapi.yaml' ]

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
      - name: Install redocly CLI
        run: npm i -g @redocly/cli
      - name: Generate diff and update CHANGELOG
        run: |
          set -e
          redocly diff origin/main~1:docs/api/openapi.yaml docs/api/openapi.yaml --format plain > api.diff || true
          if [ -s api.diff ]; then
            echo "## $(date -u +%Y-%m-%d) – API changes" >> docs/api/CHANGELOG.md
            echo "" >> docs/api/CHANGELOG.md
            echo '```' >> docs/api/CHANGELOG.md
            cat api.diff >> docs/api/CHANGELOG.md
            echo '```' >> docs/api/CHANGELOG.md
            git config user.name "CERTEUS Bot"
            git config user.email "bot@users.noreply.github.com"
            git add docs/api/CHANGELOG.md
            git commit -m "docs(api): update API CHANGELOG [skip ci]" || true
            git push
          else
            echo "No API changes detected"
          fi

