# +-------------------------------------------------------------+
# |                          CERTEUS                            |
# +-------------------------------------------------------------+
# | FILE: .github/workflows/asset-guard.yml                   |
# | ROLE: Project YAML manifest.                                |
# | PLIK: .github/workflows/asset-guard.yml                   |
# | ROLA: Manifest YAML projektu.                               |
# +-------------------------------------------------------------+

name: asset-guard
on: [push, pull_request]
jobs:
  check-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Assert required assets exist
        run: |
          set -Eeuo pipefail
          req=(
            "docs/assets/brand/certeus-banner-dark.png"
            "docs/assets/brand/certeus-banner-light.png"
            "docs/assets/brand/certeus-readme-banner.svg"
            "docs/assets/brand/certeus-favicon.svg"
            "docs/assets/brand/certeus-og.png"
            "clients/web/public/brand/favicon.svg"
            "clients/web/public/brand/site.webmanifest"
          )
          for f in "${req[@]}"; do
            [[ -f "$f" ]] || { echo "::error file=$f::missing"; exit 1; }
          done

  pr-summary:
    if: github.event_name == 'pull_request' && always()
    needs: [check-assets]
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR with Asset-Guard result
        uses: actions/github-script@v7
        with:
          script: |
            const result = '${{ needs["check-assets"].result }}';
            const body = `✔ asset-guard: ${result}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body,
            });
