name: auto-open-pr

on:
  push:
    branches:
      - "chore/**"

permissions:
  contents: read
  pull-requests: write

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Open PR to main if not exists
        uses: actions/github-script@v7
        with:
          script: |
            const branchRef = context.ref; // e.g. refs/heads/chore/apply-certeus-package
            const headBranch = branchRef.replace('refs/heads/', '');
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const base = 'main';

            // Check if PR already exists
            const { data: prs } = await github.rest.pulls.list({ owner, repo, state: 'open', head: `${owner}:${headBranch}`, base });
            if (prs.length > 0) {
              core.info(`PR already exists: #${prs[0].number}`);
              return;
            }

            const title = `chore: integrate CERTEUS gates/docs on ${headBranch}`;
            const body = [
              'Automated PR created by auto-open-pr workflow.',
              '',
              '- Adds Operational Playbook, Security Policy, Diagrams',
              '- Adds real CI Gates (Gauge/Coverage/Boundary/SLO)',
              '- Adds supply-chain provenance + cosign sign/verify',
              '- Adds packs/fin/lexqft/chatops/mailops/ethics endpoints',
              '- Publishes OpenAPI (Pages) and adds OpenAPI diff checks',
              '',
              'Please review and merge.'
            ].join('\n');

            const { data: pr } = await github.rest.pulls.create({ owner, repo, title, head: headBranch, base, body });
            // Add labels if available
            try {
              await github.rest.issues.addLabels({ owner, repo, issue_number: pr.number, labels: ['chore','ci','docs'] });
            } catch (e) {
              core.info('Could not add labels');
            }
