# +-------------------------------------------------------------+
# |                          CERTEUS                            |
# +-------------------------------------------------------------+
# | FILE: .github/workflows/branch-protection.yml             |
# | ROLE: Project YAML manifest.                                |
# | PLIK: .github/workflows/branch-protection.yml             |
# | ROLA: Manifest YAML projektu.                               |
# +-------------------------------------------------------------+

name: Enforce Branch Protection (Smoke Required)

on:
  push:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to protect
        default: main
        required: true

permissions:
  contents: read

jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - name: Check ADMIN_TOKEN availability
        id: check
        run: |
          if [ -n "${{ secrets.ADMIN_TOKEN }}" ]; then
            echo "has_token=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_token=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Set required status checks for Smoke (per OS)
        if: steps.check.outputs.has_token == 'true'
        env:
          GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          set -euo pipefail
          REPO='${{ github.repository }}' # format: owner/repo
          owner="${REPO%%/*}"
          repo="${REPO##*/}"
          # Determine branch: input if manual, else current ref name
          if [ -n "${{ inputs.branch }}" ]; then branch='${{ inputs.branch }}'; else branch='${{ github.ref_name }}'; fi
          data='{
            "required_status_checks": {"strict": true, "contexts": ["Smoke (ubuntu-latest)", "Smoke (windows-latest)"]},
            "enforce_admins": true,
            "required_pull_request_reviews": {"dismiss_stale_reviews": true, "required_approving_review_count": 1},
            "restrictions": null,
            "allow_force_pushes": false,
            "allow_deletions": false
          }'
          url="https://api.github.com/repos/${owner}/${repo}/branches/${branch}/protection"
          code=$(curl -sS -o /tmp/resp.json -w "%{http_code}" -X PUT "$url" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -d "$data")
          echo "HTTP $code for branch protection update on ${owner}/${repo}@${branch}"
          if [ "$code" -lt 200 ] || [ "$code" -ge 300 ]; then
            echo "Response body:" && cat /tmp/resp.json
            exit 1
          fi
      - name: Skip note (no ADMIN_TOKEN)
        if: steps.check.outputs.has_token != 'true'
        run: |
          echo "ADMIN_TOKEN not set; skipping branch protection update (safe no-op)."
