name: Enforce Branch Protection (Smoke Required)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to protect
        default: main
        required: true

permissions:
  contents: read

jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure ADMIN_TOKEN is available
        run: |
          if [ -z "${{ secrets.ADMIN_TOKEN }}" ]; then
            echo "ADMIN_TOKEN secret not set. Please create a classic PAT with 'repo' scope and add as repo secret ADMIN_TOKEN." >&2
            exit 1
          fi
      - name: Set required status checks for Smoke (per OS)
        env:
          GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          owner='${{ github.repository_owner }}'
          repo='${{ github.event.repository.name || github.event.repository }}'
          branch='${{ inputs.branch }}'
          contexts='["Smoke (ubuntu-latest)","Smoke (windows-latest)"]'
          gh api -X PUT repos/$owner/${{ github.event.repository.name }}/branches/$branch/protection \
            -H 'Accept: application/vnd.github+json' \
            -f required_status_checks.strict=true \
            -f required_status_checks.contexts:=$contexts \
            -f enforce_admins=true \
            -f required_pull_request_reviews.dismiss_stale_reviews=true \
            -f required_pull_request_reviews.required_approving_review_count=1 \
            -f restrictions= \
            -F allow_force_pushes=false \
            -F allow_deletions=false
