# +-------------------------------------------------------------+
# |                          CERTEUS                            |
# +-------------------------------------------------------------+
# | FILE: .github/workflows/canary_gate.yml                   |
# | ROLE: Canary/progressive readiness (PR-only)                |
# +-------------------------------------------------------------+

name: Canary-Gate

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  canary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            pyproject.toml
            constraints/**
      - name: Install deps (minimal)
        run: |
          python -m pip install -U pip wheel setuptools
          python -m pip install fastapi httpx uvicorn
      - name: Run Canary Gate
        env:
          CANARY_COUNT: '60'
          CANARY_MAX_P95_MS: '280'
          CANARY_MAX_ERROR_RATE: '0.02'
        run: |
          python scripts/gates/canary_gate.py --phases 3 --count "$CANARY_COUNT" --p95-max "$CANARY_MAX_P95_MS" --error-rate-max "$CANARY_MAX_ERROR_RATE" --out out/canary.json
      - name: Upload canary report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: canary-${{ github.sha }}
          path: out/canary.json
          if-no-files-found: warn
