# +-------------------------------------------------------------+
# |                          CERTEUS                            |
# +-------------------------------------------------------------+
# | FILE: .github/workflows/ci.yml                            |
# | ROLE: Main CI workflow for Certeus                         |
# +-------------------------------------------------------------+

name: ci

on:
  push:
    branches: [main, work/daily]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip==24.2 wheel==0.44.0 setuptools==75.1.0
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m pip install -e . || echo "No setup.py/pyproject.toml found"
          python -m pip install pytest==8.3.3 pytest-xdist==3.6.0 ruff==0.6.7 mypy==1.11.2 || true

      - name: Lint with Ruff
        continue-on-error: true
        run: |
          python -m ruff check . || true

      - name: Type check with MyPy
        continue-on-error: true
        run: |
          python -m mypy --ignore-missing-imports . || true

      - name: Run tests
        continue-on-error: true
        run: |
          python -m pytest -v || true

  build:
    name: Build Check
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v5
        with:
          python-version: "3.11"

      - name: Build package
        continue-on-error: true
        run: |
          python -m pip install --upgrade pip==24.2 wheel==0.44.0 setuptools==75.1.0 build==1.2.2
          python -m build || true
