# +-------------------------------------------------------------+
# |                          CERTEUS                            |
# +-------------------------------------------------------------+
# | FILE: .github/workflows/denylist-check.yml                  |
# | ROLE: Block PR/push if denylisted paths are touched         |
# | PLIK: .github/workflows/denylist-check.yml                  |
# | ROLA: Blokuje PR/push gdy naruszona czarna lista            |
# +-------------------------------------------------------------+

name: Denylist-Check

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  filter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Paths filter (denylist)
        id: filter
        uses: dorny/paths-filter@v3
        with:
          token: ${{ github.token }}
          filters: |
            deny:
              - 'docs/internal/**'
              - 'legal/**'
              - 'evidence/**'
              - 'finance/**'
              - 'notes/**'
              - 'drafts/**'
              - '*.docx'
              - '*.xlsx'
              - '**/*.pem'
              - '**/*.key'
              - '**/id_rsa*'
              - '**/id_ed25519*'
      - name: Fail on denylist
        if: steps.filter.outputs.deny == 'true'
        run: |
          echo "Denylist patterns matched changed files. Aborting." >&2
          exit 1
