# +-------------------------------------------------------------+
# |                          CERTEUS                            |
# +-------------------------------------------------------------+
# | FILE: .github/workflows/docs-ci.yml                        |
# | ROLE: Build docs and run link check on PR/main.            |
# +-------------------------------------------------------------+

name: docs-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: docs-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docs:
    name: Build MkDocs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install MkDocs
        run: |
          python -m pip install --upgrade pip
          python -m pip install mkdocs mkdocs-material
      - name: Build docs
        run: |
          mkdocs build -f certeus/mkdocs.yml
      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-${{ github.sha }}
          path: certeus/site

  link-check:
    name: Link Check (Markdown/HTML)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lychee link check
        uses: lycheeverse/lychee-action@v2
        with:
          # Accept 200/204 and rate-limited 429; be gentle on concurrency
          args: >-
            --no-progress --verbose --max-concurrency 8 --retry 2 --timeout 20
            --accept 200,204,429
            --exclude "localhost" --exclude "127.0.0.1" --exclude "0.0.0.0"
            --exclude "mailto:*" --exclude "tel:*"
            "certeus/**/*.md" "certeus/**/*.html"
