# +-------------------------------------------------------------+
# |                          CERTEUS                            |
# +-------------------------------------------------------------+
# | FILE: .github/workflows/openapi-pages.yml                 |
# | ROLE: Project YAML manifest.                                |
# | PLIK: .github/workflows/openapi-pages.yml                 |
# | ROLA: Manifest YAML projektu.                               |
# +-------------------------------------------------------------+

name: openapi-pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "openapi-pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v5
        with:
          python-version: "3.11"
      - name: Install PyYAML
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml
      - name: Convert OpenAPI YAML to JSON
        run: |
          python - << 'PY'
          import json, pathlib
          import yaml
          p = pathlib.Path('docs/openapi/certeus.v1.yaml')
          data = yaml.safe_load(p.read_text(encoding='utf-8'))
          out = pathlib.Path('site/openapi')
          out.mkdir(parents=True, exist_ok=True)
          (out / 'openapi.json').write_text(json.dumps(data, indent=2), encoding='utf-8')
          PY
      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
        with:
          path: site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
