# +-------------------------------------------------------------+
# |                          CERTEUS                            |
# +-------------------------------------------------------------+
# | FILE: .github/workflows/promote-daily-to-main.yml          |
# | ROLE: Auto-promote work/daily to main (gated by CI)         |
# | PLIK: .github/workflows/promote-daily-to-main.yml          |
# | ROLA: Auto-promocja work/daily → main (po zielonym CI)      |
# +-------------------------------------------------------------+

name: Promote-Daily-To-Main

on:
  workflow_run:
    workflows:
      - ci-gates
    types: [completed]
  push:
    branches: [ work/daily ]
  workflow_dispatch:
    inputs:
      force:
        description: 'Bypass weekly marker and force promotion'
        required: false
        default: 'false'

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  promote:
    runs-on: self-hosted
    steps:
      - name: Decide whether to evaluate promotion
        id: cond
        uses: actions/github-script@v7
        with:
          script: |
            const evt = context.eventName;
            let ok = true;
            if (evt === 'workflow_run') {
              const wr = context.payload.workflow_run || {};
              ok = (wr.head_branch === 'work/daily' && wr.conclusion === 'success');
            } else if (evt === 'push') {
              ok = (context.ref === 'refs/heads/work/daily');
            }
            core.setOutput('ok', ok ? 'true' : 'false');
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure git user
        shell: pwsh
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Determine SHA for evaluation
        id: sha
        if: steps.cond.outputs.ok == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const evt = context.eventName;
            let sha;
            if (evt === 'workflow_run') sha = context.payload.workflow_run?.head_sha;
            else sha = context.sha;
            core.setOutput('sha', sha);
      - name: Determine if weekly promotion is requested
        id: marker
        if: steps.cond.outputs.ok == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const force = (context.payload?.inputs?.force === 'true');
            let promote = false;
            if (force) {
              promote = true;
            } else {
              const sha = core.getInput('sha', { required: false }) || '${{ steps.sha.outputs.sha }}';
              const { data: commit } = await github.rest.repos.getCommit({ owner: context.repo.owner, repo: context.repo.repo, ref: sha });
              const msg = commit?.commit?.message || '';
              core.info('Commit message for '+sha+':\n'+msg);
              promote = /\[week-end\]/i.test(msg) || /^weekly-promote:\s*(true|1)/mi.test(msg);
            }
            core.setOutput('promote', promote ? 'true' : 'false');
      # ci-gates conclusion is already 'success' by job condition above${insert}
      - name: Append WORKLOG on work/daily (pre-merge)
        if: steps.cond.outputs.ok == 'true' && steps.marker.outputs.promote == 'true'
        env:
          SHA: ${{ github.event.workflow_run.head_sha }}
          ACTOR: ${{ github.actor }}
        shell: pwsh
        run: |
          git checkout work/daily
          $ts = [DateTime]::UtcNow.ToString('yyyy-MM-dd HH:mm:ssZ')
          $branch = 'work/daily'
          $summary = "auto-promote: ${env:SHA} (gates green)"
          $details = @(
            'Gates: Proof Gate, asset-guard, Gauge-Gate, Path-Coverage-Gate, Boundary-Rebuild-Gate',
            "Actor: ${env:ACTOR}"
          ) -join "`n"
          $entry = "- $ts [${env:ACTOR}] ($branch): $summary`n  - " + ($details -replace "`n","`n  - ") + "`n"
          if (-not (Test-Path WORKLOG.md)) { "# CERTEUS - WORKLOG`n`n" | Out-File -FilePath WORKLOG.md -Encoding UTF8 }
          Add-Content -Path WORKLOG.md -Value $entry -Encoding UTF8
          git add WORKLOG.md
          git commit -m "chore(worklog): $summary" || exit 0
          git push origin work/daily || exit 0
      - name: Fast-forward main to work/daily (if possible)
        if: steps.cond.outputs.ok == 'true' && steps.marker.outputs.promote == 'true'
        id: ff
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: |
          git fetch origin
          git checkout main
          git reset --hard origin/main
          git merge --ff-only origin/work/daily 2>$null
          if ($LASTEXITCODE -eq 0) {
            "ff=true" >> $env:GITHUB_OUTPUT
            git push origin main
          } else {
            Write-Host "No fast-forward possible; skipping (PR path)."
            "ff=false" >> $env:GITHUB_OUTPUT
          }
      - name: Create or auto-merge PR (work/daily -> main)
        if: steps.cond.outputs.ok == 'true' && steps.marker.outputs.promote == 'true' && steps.ff.outputs.ff == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            // Find existing PR
            const list = await github.rest.pulls.list({ owner, repo, state: 'open', base: 'main', head: owner+':work/daily', per_page: 1 });
            let pr = list.data[0];
            if (!pr) {
              const created = await github.rest.pulls.create({ owner, repo, base: 'main', head: 'work/daily', title: 'Promote work/daily to main', body: 'Auto-promotion after green CI.' });
              pr = created.data;
            }
            // Try to enable auto-merge (squash). Requires GraphQL.
            try {
              await github.graphql(`mutation($prId: ID!) { enablePullRequestAutoMerge(input: { pullRequestId: $prId, mergeMethod: SQUASH }) { clientMutationId } }`, { prId: pr.node_id });
            } catch (e) {
              core.warning('Could not enable auto-merge: ' + (e?.message || e));
            }
