# +-------------------------------------------------------------+
# |                          CERTEUS                            |
# +-------------------------------------------------------------+
# | FILE: .github/workflows/proofs-fs-platforms.yml           |
# | ROLE: ProofFS platform checks (macOS/Windows; optional)     |
# +-------------------------------------------------------------+

name: ProofFS Platforms (optional)

on:
  # Tylko ręcznie; domyślnie wyłączone, by nie hałasować w PR
  workflow_dispatch:

permissions:
  contents: read

jobs:
  macos:
    if: ${{ false }}
    runs-on: macos-latest
    steps:
      - run: echo "macOS path disabled"

  windows:
    if: ${{ false }}
    runs-on: windows-latest
    steps:
      - run: echo "Windows path disabled"
