name: ProofFS Self-Hosted

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  macos_selfhosted:
    name: macOS ProofFS (self-hosted)
    if: ${{ vars.ENABLE_SELF_HOSTED == '1' }}
    runs-on: [self-hosted, macos, macfuse]
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.11'
      - name: Mount smoke (macFUSE)
        run: |
          bash scripts/pfs/osx_mount_smoke.sh

  windows_selfhosted:
    name: Windows Dokan (self-hosted)
    if: ${{ vars.ENABLE_SELF_HOSTED_WINDOWS == '1' }}
    runs-on: [self-hosted, windows, dokan]
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Dokan smoke
        shell: pwsh
        run: |
          pwsh -File scripts/pfs/win_dokan_smoke.ps1
