# +-------------------------------------------------------------+
# |                          CERTEUS                            |
# +-------------------------------------------------------------+
# | FILE: .github/workflows/release.yml                       |
# | ROLE: Project YAML manifest.                                |
# | PLIK: .github/workflows/release.yml                       |
# | ROLA: Manifest YAML projektu.                               |
# +-------------------------------------------------------------+

name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract tag
        id: vars
        run: |
          ref='${GITHUB_REF_NAME}'
          echo "tag=${ref}" >> $GITHUB_OUTPUT
          echo "sha=${GITHUB_SHA}" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build & push API image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra/services/api_gateway/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-api:${{ steps.vars.outputs.tag }}
            ghcr.io/${{ github.repository }}-api:latest
            ghcr.io/${{ github.repository }}-api:${{ steps.vars.outputs.sha }}
      - name: Build & push ProofGate image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra/services/proofgate/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-proofgate:${{ steps.vars.outputs.tag }}
            ghcr.io/${{ github.repository }}-proofgate:latest
            ghcr.io/${{ github.repository }}-proofgate:${{ steps.vars.outputs.sha }}
  create-release:
    runs-on: ubuntu-latest
    needs: build-and-push-images
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
