# +-------------------------------------------------------------+
# |                          CERTEUS                            |
# +-------------------------------------------------------------+
# | FILE: .github/workflows/release-please.yml                 |
# | ROLE: Automated semver releases via Release Please         |
# +-------------------------------------------------------------+

name: release-please

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        # Use maintained action (old google-github-actions is deprecated)
        uses: googleapis/release-please-action@v4
        with:
          # Prefer PAT if provided to bypass repo setting restrictions
          token: ${{ secrets.RELEASE_PLEASE_TOKEN || github.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
