# +-------------------------------------------------------------+
# |                          CERTEUS                            |
# +-------------------------------------------------------------+
# | FILE: .github/workflows/secret-scan.yml                    |
# | ROLE: Gitleaks secret scanning (manual + nightly)          |
# | PLIK: .github/workflows/secret-scan.yml                    |
# | ROLA: Skanowanie sekretów (ręcznie + nocnie)               |
# +-------------------------------------------------------------+

name: Secret-Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: read

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install gitleaks
        uses: zricethezav/gitleaks-action@v2.3.7
        with:
          args: detect --redact --source . --config gitleaks.toml --report-format json --report-path gitleaks-report.json
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report-${{ github.sha }}
          path: gitleaks-report.json
          if-no-files-found: warn

