# +-------------------------------------------------------------+
# |                          CERTEUS                            |
# +-------------------------------------------------------------+
# | FILE: .github/workflows/security-enforce.yml              |
# | ROLE: Project YAML manifest.                               |
# | PLIK: .github/workflows/security-enforce.yml              |
# | ROLA: Manifest YAML projektu.                              |
# +-------------------------------------------------------------+

name: security-enforce

on:
  workflow_dispatch:

jobs:
  enforce:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install project
        run: |
          python -m pip install -U pip wheel setuptools
          python -m pip install -e .
      - name: Enforce Marketplace Policy
        env:
          ENFORCE_MARKETPLACE_POLICY: "1"
        run: |
          python scripts/gates/marketplace_policy_gate.py
      - name: Enforce Plugin Supply-Chain
        env:
          ENFORCE_PLUGIN_SUPPLY: "1"
        run: |
          python scripts/gates/plugin_supply_chain_gate.py
      - name: Enforce Compliance Mapping
        env:
          ENFORCE_COMPLIANCE_MAPPING: "1"
        run: |
          python scripts/gates/compliance_mapping_gate.py

