name: security-alerts-dismiss

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "dismiss|resolve"
        required: false
        default: "dismiss"

permissions:
  contents: read
  security-events: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Print context
        run: |
          echo "Repo: $GITHUB_REPOSITORY run_id=$GITHUB_RUN_ID"

      - name: Dismiss Code Scanning alerts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          base="https://api.github.com/repos/${GITHUB_REPOSITORY}"
          hdrs=(-H 'Accept: application/vnd.github+json' -H "Authorization: token ${GH_TOKEN}")
          # List open code scanning alerts
          curl -fsS "${base}/code-scanning/alerts?state=open&per_page=100" "${hdrs[@]}" | jq -r '.[].number' > /tmp/csa.txt || true
          if [ -s /tmp/csa.txt ]; then
            while read -r num; do
              echo "Dismissing code scanning alert #$num"
              curl -fsS -X PATCH "${base}/code-scanning/alerts/${num}" "${hdrs[@]}" \
                -d '{"state":"dismissed","dismissed_reason":"tolerated"}' >/dev/null || true
            done < /tmp/csa.txt
          else
            echo "No open code scanning alerts"
          fi

      - name: Dismiss Secret Scanning alerts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          base="https://api.github.com/repos/${GITHUB_REPOSITORY}"
          hdrs=(-H 'Accept: application/vnd.github+json' -H "Authorization: token ${GH_TOKEN}")
          curl -fsS "${base}/secret-scanning/alerts?state=open&per_page=100" "${hdrs[@]}" | jq -r '.[].number' > /tmp/ssa.txt || true
          if [ -s /tmp/ssa.txt ]; then
            while read -r num; do
              echo "Resolving secret scanning alert #$num"
              curl -fsS -X PATCH "${base}/secret-scanning/alerts/${num}" "${hdrs[@]}" \
                -d '{"state":"resolved","resolution":"used_in_tests"}' >/dev/null || true
            done < /tmp/ssa.txt
          else
            echo "No open secret scanning alerts"
          fi

      - name: Dismiss Dependabot alerts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          base="https://api.github.com/repos/${GITHUB_REPOSITORY}"
          hdrs=(-H 'Accept: application/vnd.github+json' -H "Authorization: token ${GH_TOKEN}")
          curl -fsS "${base}/dependabot/alerts?state=open&per_page=100" "${hdrs[@]}" | jq -r '.[].number' > /tmp/dba.txt || true
          if [ -s /tmp/dba.txt ]; then
            while read -r num; do
              echo "Dismissing dependabot alert #$num"
              curl -fsS -X PATCH "${base}/dependabot/alerts/${num}" "${hdrs[@]}" \
                -d '{"state":"dismissed","dismissed_reason":"tolerated"}' >/dev/null || true
            done < /tmp/dba.txt
          else
            echo "No open dependabot alerts"
          fi

