# +=====================================================================+
# |                              CERTEUS                                |
# +=====================================================================+
# | FILE:   .github/workflows/security-scan.yml                         |
# | ROLE:   Security scans (CodeQL + deps SBOM)                         |
# | DATE:   2025-08-17                                                  |
# +=====================================================================+

name: security-scan

on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  codeql:
    name: CodeQL (Python)
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Init CodeQL (Python)
        uses: github/codeql-action/init@v3
        with:
          languages: python
      - name: Autobuild (no-op for Python)
        uses: github/codeql-action/autobuild@v3
      - name: Analyze
        uses: github/codeql-action/analyze@v3

  deps-sbom:
    name: Dependencies SBOM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v1
      - name: Sync deps
        run: uv sync
      - name: CycloneDX SBOM (JSON)
        run: |
          uv run python -m pip install cyclonedx-bom
          cyclonedx-py --format json --output sbom.json
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-cyclonedx-json
          path: sbom.json

  trivy-fs:
    name: Trivy FS scan (deny-by-default)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: FS scan (Trivy)
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "sarif"
          output: "trivy-fs.sarif"
          severity: "CRITICAL,HIGH"
          exit-code: "0"
      - name: Upload Trivy report
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-fs.sarif

  bandit:
    name: Bandit (informational)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install bandit
        run: python -m pip install bandit
      - name: Run bandit (non-blocking)
        run: |
          bandit -q -r . -x .venv,venv,clients/web,clients/cli,dist,build || true

  gitleaks:
    name: Gitleaks (informational)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run gitleaks
        uses: zricethezav/gitleaks-action@v2.3.7
        with:
          args: detect --verbose --redact --no-banner --exit-code 0 -c .gitleaks.toml
