name: SelfHosted-CI

on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: [self-hosted, linux, codespaces]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            pyproject.toml
            constraints/**
      - name: Install deps
        run: |
          python -m pip install -U pip wheel setuptools
          python -m pip install -e .
          python -m pip install ruff pytest pytest-xdist pytest-asyncio httpx z3-solver hypothesis openapi-spec-validator PyYAML aioquic fusepy bandit
      - name: Run full test suite
        env:
          PYTEST_ADDOPTS: "-n auto --durations=15"
        run: |
          python -m pytest -q
      - name: QUIC Echo
        run: |
          openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 1 -nodes -subj "/CN=localhost"
          nohup python scripts/p2p/quic_echo.py serve --host 127.0.0.1 --port 4443 --cert cert.pem --key key.pem >/dev/null 2>&1 &
          sleep 1
          OUT=$(python scripts/p2p/quic_echo.py echo --host 127.0.0.1 --port 4443 --message hello)
          test "$OUT" = "hello"
      - name: ProofFS FUSE Smoke (Linux)
        run: |
          python -m pytest -q tests/services/test_pfs_fuse_linux.py || true
