name: SelfHosted-MacOS-CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    # Gate self-hosted macOS job to avoid queueing when runner is unavailable
    if: ${{ vars.ENABLE_SELF_HOSTED == '1' }}
    runs-on: [self-hosted, macos, macfuse]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Print runner context
        run: |
          uname -a
          sw_vers || true
          whoami
          echo "Labels: $RUNNER_LABELS"
      - name: Verify macFUSE presence
        run: |
          kextstat 2>/dev/null | grep -i fuse || echo "kext not loaded (may require approval)"
          brew --version || true
      - name: Basic Build Step
        run: echo "Build placeholder on self-hosted macOS runner"
