name: test-certeus-runner

on:
  workflow_dispatch:

jobs:
  echo-ok:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Print runner info
        run: |
          echo "OS=${{ runner.os }}"
          echo "Arch=$(uname -m)"
      - name: Say OK
        run: echo OK
