# +-------------------------------------------------------------+
# |                          CERTEUS                            |
# +-------------------------------------------------------------+
# | FILE: .github/workflows/truth_gates.yml                   |
# | ROLE: Project YAML manifest.                                |
# | PLIK: .github/workflows/truth_gates.yml                   |
# | ROLA: Manifest YAML projektu.                               |
# +-------------------------------------------------------------+

name: truth‑gates
on:
  pull_request:
    branches:
      - main
      - work/daily

jobs:
  truth-gates:
    name: truth‑gates
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            pyproject.toml
            constraints/**

      - name: Setup uv
        uses: astral-sh/setup-uv@8d55fbecc275b1c35dbe060458839f8d30439ccf # v3
        with:
          version: latest

      - name: Install deps
        run: uv sync --all-extras --dev

      - name: Prepare out dir
        run: mkdir -p out

      - name: Compute Truth Gates (AFV/ASE/ATC)
        run: uv run python scripts/compute_truth_gates.py --out out/truth_gates.json

      - name: Publish gates as PR comment
        # Skip when PR is from a fork to avoid 403
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7
        with:
          script: |
            const fs = require('fs');
            let body = 'Truth Gates (AFV/ASE/ATC):\\n';
            try {
              const data = JSON.parse(fs.readFileSync('out/truth_gates.json', 'utf8'));
              body += '```json\\n' + JSON.stringify(data, null, 2) + '\\n```';
            } catch (e) {
              body += '_failed to read out/truth_gates.json_';
            }
            try {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body
              });
            } catch (err) {
              core.warning(`Could not create PR comment: ${err?.message || err}`);
            }
