# +-------------------------------------------------------------+
# |                          CERTEUS                            |
# +-------------------------------------------------------------+
# | FILE: .github/workflows/ui-demos.yml                       |
# | ROLE: Run UI/demo smokes (optional, PR info only).          |
# | PLIK: .github/workflows/ui-demos.yml                       |
# | ROLA: Uruchamia smoki UI/demo (opcjonalne, info w PR).      |
# +-------------------------------------------------------------+

name: UI Demos

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  demos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          version: latest
      - name: Run demos (continue on error)
        continue-on-error: true
        run: |
          set -euxo pipefail
          mkdir -p reports
          uv run --with-requirements requirements.txt --with httpx --with cryptography -q python scripts/smokes/w4_sequence_demo.py || true
          uv run --with-requirements requirements.txt --with httpx --with cryptography -q python scripts/smokes/w4_sequence_compare_demo.py || true
          uv run --with-requirements requirements.txt --with httpx --with cryptography -q python scripts/smokes/w6_devices_demo.py || true
          uv run --with-requirements requirements.txt --with httpx --with cryptography -q python scripts/smokes/w7_fin_demo.py || true
          uv run --with-requirements requirements.txt --with httpx --with cryptography -q python scripts/smokes/w8_lexenith_demo.py || true
      - name: Upload demo reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-demos-${{ github.sha }}
          path: reports/*.json
          if-no-files-found: warn
      - name: Comment PR with demo summary
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let files = [];
            try { files = fs.readdirSync('reports').filter(f=>f.endsWith('.json')); } catch {}
            if (!files.length) {
              core.info('No demo reports to summarize');
              return;
            }
            let body = '### UI Demos Reports\n\n';
            for (const f of files) body += `- ${f}\n`;
            try {
              await github.rest.issues.createComment({ owner: context.repo.owner, repo: context.repo.repo, issue_number: context.issue.number, body });
            } catch (e) {
              core.warning(`Comment failed: ${e?.message||e}`);
            }
