services:
  gha-runner:
    image: myoung34/github-runner:latest
    container_name: gha-runner-linux
    environment:
      # Required: target repository URL
      REPO_URL: https://github.com/CERTEUS/certeus
      # One of (prefer ephemeral RUNNER_TOKEN):
      #  - RUNNER_TOKEN: ${RUNNER_TOKEN}
      #  - GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      # Optional: if you use a PAT instead of ephemeral token, uncomment below
      # GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}

      RUNNER_NAME: ${RUNNER_NAME:-lin-build-01}
      RUNNER_LABELS: self-hosted,linux,docker,build
      RUNNER_WORKDIR: /_work
      # Ephemeral runner is safer for CI
      EPHEMERAL: "true"
    volumes:
      - runner_work:/_work
    restart: unless-stopped

volumes:
  runner_work:
